name: Publish
on: 
  push:
    branches: 
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Vuepress
      run: npm install -g vuepress@^1.2.0
    - name: Build Vuepress
      run: npm run build
      env:
        CI: true
    - name: Push
      run: ./scrips/ci_deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


